###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6d73b0dc-fd8a-4f4a-9b16-bf075c2985e0/345ca37b7db49d9528406707aa97ff6c/aspnetcore-runtime-8.0.1-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "ee3960eeceda5023b43448bf3df8d532"
SRC_URI[sha256sum] = "2f0a24b5f40b3b6947f5a37a6f73f83f223695886b40b9f4ce3b382ab213a81a"

