###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6d3049cc-4dcf-4dfb-9444-009997fbe620/fa9da42c88a2d74aef7e99f56269e36d/aspnetcore-runtime-8.0.0-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "84e32b767981d3b21412cc93cc54d944"
SRC_URI[sha256sum] = "dc89239d90011b8e373c796c22b91a72d90fe22110b984e18e7758a29270d49d"

