###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/91223e4e-2300-4e8e-9364-09ea1c317294/47fb26a2df5eeee08f77a4d1b720a34a/aspnetcore-runtime-8.0.0-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "e6c0943f4b6801382a5b47d8b20092fc"
SRC_URI[sha256sum] = "09ac683722a29d0dbe49e3c7604a641a787335a6b4e2adf5a0bd43575c665e78"
