###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0688a08e-fdaf-489b-90e4-033cc19cfffc/c9a9c648862b0b18c9aca77d3be0ef9f/aspnetcore-runtime-8.0.1-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b94989a06a01d164302e074511476d3a"
SRC_URI[sha256sum] = "4419289855f180dd689826925b829fa9cb0e57852c5a593acd929143be72243e"
