###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/91223e4e-2300-4e8e-9364-09ea1c317294/47fb26a2df5eeee08f77a4d1b720a34a/aspnetcore-runtime-8.0.0-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "e6c0943f4b6801382a5b47d8b20092fc"
SRC_URI[sha256sum] = "2c501257aa5f7437ab7cbc7419b3a4368ad2b72b515b3f3f9acfd83c0b75d057"
