###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/257bdcc7-cbfd-4680-964a-cbe8e9160bca/ac0cbf19d897ba51ae004b4146940a0a/aspnetcore-runtime-8.0.0-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "47c4b9b4a915cc26a15933c0b174312f"
SRC_URI[sha256sum] = "4418b2169d5f3bb33064e40e34f2cff0f67659dcd3fb0f3c9355b2b69e688964"
