###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8e19b03a-93be-43ae-8cd6-95b89a849572/facbb896d726a2496dd23bcecb28c9e9/aspnetcore-runtime-8.0.1-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b881364c1ccbbb9a947ef6dd10fd3348"
SRC_URI[sha256sum] = "cd825a5bd7b40e5706840d7b22650b787f71db5e2e496c80e16571bf5003f8fe"
