###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/809134e8-66fa-4f0c-a84a-9e981e9bd2f9/efb33d1a4075101410c82a617f4f7c42/dotnet-runtime-8.0.1-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "2e12004765f7a9b00b662d662f24ed92"
SRC_URI[sha256sum] = "6aeb840cf7980fa14b094f75e4bde3f64463a284b2c9a55952a28337529c562e"
