###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/c879318f-48f3-4cc4-8dcc-a6b77cfdfc38/7890f8a96ea335f5265cd1aa80cac8ce/dotnet-runtime-8.0.0-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "4cebd6b3133f7432e38bac0db4b30981"
SRC_URI[sha256sum] = "09ac683722a29d0dbe49e3c7604a641a787335a6b4e2adf5a0bd43575c665e78"

