###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/4d5166de-c1ac-45c5-bb8a-d47f8ee93ad9/ffab59440a3eb74359dd3009e4da5a81/dotnet-runtime-8.0.1-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "720aea190526a594fa1d6371f2ec80dc"
SRC_URI[sha256sum] = "d33ecf6f475a23d6058f682cfb1f84eb9bc67542ae864dc480537fc3456b9cbc"
